# Generated by Django 5.1.3 on 2024-11-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollos', '0002_booktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktitle',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='book_files/'),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='attach_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='code_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='material_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='num_of_copies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='standard_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='starting_barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='sub_location',
            field=models.CharField(blank=True, choices=[('circulation', 'Circulation'), ('floor1', 'Floor 1'), ('floor2', 'Floor 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booktitle',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
