# Generated by Django 5.1.3 on 2024-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollos', '0003_booktitle_attach_file_booktitle_attach_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktitle',
            name='standard_numbers',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
