# Generated by Django 5.1.3 on 2024-11-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollos', '0004_alter_booktitle_standard_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktitle',
            name='standard_numbers',
            field=models.CharField(blank=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
