# Generated by Django 5.1.3 on 2024-12-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apollos', '0005_alter_booktitle_standard_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
