# Generated by Django 5.1.3 on 2024-12-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollos', '0009_alter_booktitle_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktitle',
            name='material_type',
            field=models.CharField(blank=True, choices=[('e-Book', 'E-Book'), ('e-Journal', 'E-Journal'), ('manuscript', 'Manuscript')], max_length=100, null=True),
        ),
    ]
