# Generated by Django 5.1.3 on 2024-12-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollos', '0010_alter_booktitle_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_count', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_books', to='apollos.booktitle')),
            ],
        ),
    ]
