# Generated by Django 5.1.3 on 2024-12-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollos', '0011_trendingbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktitle',
            name='material_type',
            field=models.CharField(choices=[('e-Book', 'E-Book'), ('e-Journal', 'E-Journal'), ('manuscript', 'Manuscript')], default='E-Book', max_length=100),
        ),
    ]
