# Generated by Django 5.1.3 on 2024-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollos', '0012_alter_booktitle_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktitle',
            name='material_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
